// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
void call_report_from_cpp();
extern "C" SEXP _parentframecpp_call_report_from_cpp() {
  BEGIN_CPP11
    call_report_from_cpp();
    return R_NilValue;
  END_CPP11
}
// code.cpp
cpp11::sexp call_cleanup_from_cpp();
extern "C" SEXP _parentframecpp_call_cleanup_from_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(call_cleanup_from_cpp());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_parentframecpp_call_cleanup_from_cpp", (DL_FUNC) &_parentframecpp_call_cleanup_from_cpp, 0},
    {"_parentframecpp_call_report_from_cpp",  (DL_FUNC) &_parentframecpp_call_report_from_cpp,  0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_parentframecpp(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
