# Generated by cpp11: do not edit by hand

call_report_from_cpp <- function() {
  invisible(.Call(`_parentframecpp_call_report_from_cpp`))
}

call_cleanup_from_cpp <- function() {
  .Call(`_parentframecpp_call_cleanup_from_cpp`)
}

call_error_from_cpp <- function(x) {
  invisible(.Call(`_parentframecpp_call_error_from_cpp`, x))
}
